// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIfrpNQ_m-PBHtdr-07K7IvSubRCI2RlE',
    appId: '1:324948581496:web:d34f704286b7dafc97e18d',
    messagingSenderId: '324948581496',
    projectId: 'flutterchatapp-8edc5',
    authDomain: 'flutterchatapp-8edc5.firebaseapp.com',
    storageBucket: 'flutterchatapp-8edc5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdFvDUxoB736XokfRVYTAoUqC2ef0pY2M',
    appId: '1:324948581496:android:2319d4dff43d3ece97e18d',
    messagingSenderId: '324948581496',
    projectId: 'flutterchatapp-8edc5',
    storageBucket: 'flutterchatapp-8edc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk5eaaUCIScPaTEqCXdwVQQpFA0_0L1oM',
    appId: '1:324948581496:ios:544dc1cdd57e654b97e18d',
    messagingSenderId: '324948581496',
    projectId: 'flutterchatapp-8edc5',
    storageBucket: 'flutterchatapp-8edc5.appspot.com',
    iosBundleId: 'com.example.chatMassangerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk5eaaUCIScPaTEqCXdwVQQpFA0_0L1oM',
    appId: '1:324948581496:ios:6605327f8892ab6497e18d',
    messagingSenderId: '324948581496',
    projectId: 'flutterchatapp-8edc5',
    storageBucket: 'flutterchatapp-8edc5.appspot.com',
    iosBundleId: 'com.example.chatMassangerApp.RunnerTests',
  );
}
